### ISSUE TITLE
bundle-stats  plugin is crushed  with DuplicatesPlugin

### ISSUE THREAD

**Issue by micromechanika** [relative-ci/bundle-stats#2029]
when use `const { DuplicatesPlugin } = require('inspectpack/plugin');` in stats.json file create information about duplicates.
And then  **bundle-stats**  plugin is crushed  
can you fix that behavior 
<img width="954" alt="Screen Shot 2022-02-03 at 02 23 45" src="https://user-images.githubusercontent.com/60350628/152261236-388569a1-910e-4e82-a4f3-f039e2ee07a4.png">

**Comment by vio** [comment]
@micromechanika bundle-stats expects a valid JSON file, node `require` is failing to load `stats.json` file due to the extra characters at the beginning of the JSON file ('Duplicate sources ...').

If you are generating the stats using `--json`, try to pass the output path as an argument and not as a stdout redirect:

```diff
- webpack --json > stats.json
+ webpack --json=stats.json
```
